package network;

public enum TypeMessage {
    VERBAL_MESSAGE,
    SERVICE_MESSAGE_AUTHORIZATION,
    SERVICE_MESSAGE_UPDATE_LIST_USERS,
    SERVICE_MESSAGE_UPDATE_DIALOGUES,
    SERVICE_MESSAGE_IS_LOGGED
}
